### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by licaon-kter** [sz3/cfc#16]
Google sdkmanager has `3.18.1`

Debian stable has `3.18.4` https://packages.debian.org/bullseye/cmake

Google sdkmanager has `3.22.1`

Debian stable backports has `3.25.1` https://packages.debian.org/bullseye-backports/cmake

But you want `3.16.3` https://github.com/sz3/cfc/blob/v0.5.12/app/build.gradle#L32

Can this be changed to those that are easily available?

I can force it before the F-Droid build https://gitlab.com/fdroid/fdroiddata/-/blob/f9bd350d3e85c60a5e0a3402acc51344bb17dabc/metadata/org.cimbar.camerafilecopy.yml#L56

But maybe this is easier to setup here upstream.

**Comment by sz3** [comment]
Sounds reasonable; I'll try out one of the newer cmakes (probably one of the `3.18.x`s) and see how it goes.

**Comment by sz3** [comment]
Ok, I tested 3.18.4 locally and it seems fine.

I've pushed a commit to unpin the cmake dependency (https://github.com/sz3/cfc/commit/5cee278bce8dfa1e200b716c1109aee1d963538b) -- let me know if that works.

Older cmake versions (e.g. `3.18.x`) are probably the safest bet for now, since I don't know what deprecation warnings I might be running afoul of.

**Comment by licaon-kter** [comment]
Yup, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/2a6a29c942e3315ebc320bf7f0b914fe9f26531d
