### ISSUE TITLE
Does this app work at all?

### ISSUE THREAD

**Issue by HarriBuh** [sz3/cfc#24]
I followed the instructions 1:1 any yet, the app does neither recognise the code I uploaded nor does it show ANY signs of progression at all. There is no "Make foto"-button or similar feature to at least trigger the processing manually.
I find it hard to like silent apps that don't work.

**Comment by sz3** [comment]
Sorry to hear that.

It's hard to say for sure what the problem you're running into is, but the most likely culprit is that the color decode is failing. There are some things you could try (changing color temperature on the sender screen, e.g. "night mode"), but the root of the issue is that some cameras struggle with color reproduction, and the initial version of cimbar -- the one that we're using -- needs both the symbols and colors to decode in order to work.

I'm considering a change to the format that should allow it to succeed (at slower speeds) even if the color decodes fail.

> There is no "Make foto"-button or similar feature to at least trigger the processing manually.

There's no manual step that would help here. The decode is failing because either the symbols aren't being read properly (this happens if the code is too small, or the camera resolution too low), or the colors aren't being read properly (more common, since the color decode logic isn't the best).
