### ISSUE TITLE
"App not installed" error

### ISSUE THREAD

**Issue by OverPaw** [sz3/cfc#6]
CameraFileCopy is failed to install, but system requirements seem to match.
My phone with Snapdragon 439 processor has 4+4 Cortex-A53 cores operating under Android 9.

**Comment by sz3** [comment]
Is there an error message?

I feel like that *should* work (it's arm64-v8, as far as I know). But android can be a bit mysterious...

**Comment by OverPaw** [comment]
It is "App not installed" error. I've read through the topic at stackoverflow on it and tried to disable Google Play Protect, but it didn't help. Probably the problem is with building of apk or with its signature.

**Comment by sz3** [comment]
Unfortunately, I don't have a good answer for this. At best, I can enumerate some things that *might* explain the issue:

1. play protect can stop the install. You mentioned turning it off, so this probably isn't your issue. Airplane mode may also be useful for this?
2. apk file is on SD card instead of internal storage -- I don't know why this should matter, but it does sometimes?
3. inadequate storage space -- this is a long shot, but apparently running out of space results in the generic error
4. apps from unknown sources are disabled -- do other apks install (not via google play) on the phone? There may be a setting under "Lock screen and security" that helps.
5. I think I've seen app permissions cause this before? The app you're trying to install the apk from (I use the Files app) needs permissions to install apps -- but *usually* if this is the problem, you'll get a helpful error message instead of the generic "app not installed".

I'll update this issue if I learn anything new.

**Comment by OverPaw** [comment]
It turns out that, despite arm64-v8a processor, my phone has armeabi-v7a operating system. See the screenshot. There are no problems with installing and running CFC on other phones with true AArch64 instruction set support. I think minor corrections to system requirements can be made.
![deviceinfohw](https://user-images.githubusercontent.com/64133542/124383184-ab97e200-dcd3-11eb-9389-283dcaca8ad5.jpg)

**Comment by sz3** [comment]
Interesting! :thinking: 

Thanks for the update, I appreciate it. :)
